services:
  reth:
    image: ghcr.io/paradigmxyz/reth:latest
    container_name: reth-dev
    restart: unless-stopped
    command: >
      node
      --dev
      --http
      --http.addr 0.0.0.0
      --http.port 8545
      --http.api web3,eth,net,debug,trace,txpool
      --http.corsdomain "*"
      --ws
      --ws.addr 0.0.0.0
      --ws.port 8546
      --ws.api web3,eth,net,debug,trace,txpool
      --ws.origins "*"
      --metrics 0.0.0.0:9001
      --authrpc.addr 0.0.0.0
      --authrpc.port 8551
      --authrpc.jwtsecret /data/jwt.hex
      --datadir /data
      --dev.block-time 12s
    ports:
      - "8545:8545"   # HTTP RPC
      - "8546:8546"   # WebSocket RPC
      - "9001:9001"   # Metrics
      - "8551:8551"   # Engine API
      - "30303:30303" # P2P
    volumes:
      - reth_data:/data
      - ./jwt.hex:/data/jwt.hex:ro
    networks:
      - eth-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - eth-network
    depends_on:
      - reth

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    networks:
      - eth-network
    depends_on:
      - prometheus

volumes:
  reth_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  eth-network:
    driver: bridge